#!/bin/zsh
# by randomowo

# homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# macos dev-tools
export PATH="/Applications/Xcode.app/Contents/Developer/usr/bin:$PATH"

# PATH
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/opt/homebrew/opt/gnu-getopt/bin:$PATH"
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubun:$PATH"
export PATH="$HOME/.local/bin:$PATH"

export PATH="/opt/homebrew/opt/openssl@3/bin:$PATH"
export PATH="/opt/homebrew/opt/e2fsprogs/sbin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"

# mise-cli
eval "$(mise activate ${SHELL##*/})"
export PATH="$HOME/.local/share/mise/shims:$PATH"

# go installed bins hack
export GOBIN="$HOME/go/bin"
export PATH="$GOBIN:$PATH"

# rust
export RUSTUP_HOME="$HOME/.local/share/rustup"
export CARGO_HOME="$HOME/.local/share/cargo"
[ -d "$CARGO_HOME" ] && source "${CARGO_HOME}/env"

export PATH="$CARGO_HOME/bin:$PATH"

# Toolbox
export PATH="$PATH:$HOME/Library/Application Support/JetBrains/Toolbox/scripts"

# kubectl packag emanager (krew)
export PATH="${KREW_ROT:-$HOME/.krew}/bin:$PATH"

# zoxide
type zoxide>/dev/null && eval "$(zoxide init --cmd cd zsh)"

# fzf
type fzf>/dev/null && source <(fzf --zsh)

# colima
export COLIMA_HOME="$HOME/.colima"

# ollama

# disable ollama cloud features
OLLAMA_NO_CLOUD=1

# reducee memory use for context size grows
OLLAMA_FLASH_ATTENTION=1

# context quantization
# f16 - default 15bit per parameter
# q8_0 - 1/2 of f16
# q4_0 - 1/4 of f16
OLLAMA_KV_CACHE_TYPE=q8_0
