theme = "gruvbox"

[editor]
line-number = "relative"
mouse = false
shell=["/bin/zsh", "-c"]
auto-completion = true
auto-format = true
auto-save = false
true-color = false

[editor.statusline]
left = ["mode", "diagnostics", "spinner"]
center = ["file-name", "total-line-numbers"]
right = ["version-control", "separator", "position", "separator", "file-line-ending", "file-encoding", "file-type"]
separator = ":"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "_"
tab = ">"
newline = "\n"
tabpad = "." # Tabs will look like "→···" (depending on tab width)

[editor.soft-wrap]
enable = false

[editor.smart-tab]
enable = true

## Mappings
[keys.normal]

[keys.select]

[keys.select.g]
c = "toggle_comments"

[keys.insert]
