theme = "gruvbox"

[editor]
line-number = "absolute"
mouse = false
middle-click-paste = true
shell = ["/bin/zsh", "-c"]
auto-completion = true
auto-format = false
continue-comments = false
true-color = false
text-width = 120
rulers = [120]
idle-timeout = 10
bufferline = "always"
cursorline = true
end-of-line-diagnostics = "disable"

[editor.auto-save]
focus-lost = true

[editor.statusline]
left = ["mode", "diagnostics", "version-control"]
center = ["file-base-name", "file-modification-indicator", "total-line-numbers"]
right = ["position", "file-line-ending", "file-encoding", "file-type"]
separator = ":"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true
display-inlay-hints = true
auto-signature-help = false

[editor.inline-diagnostics]
cursor-line = "disable"
other-lines = "disable"

[editor.search]
smart-case = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "_"
tab = ">"
newline = "\n"
tabpad = "." # Tabs will look like ">···" (depending on tab width)

[editor.indent-guides]
render = false

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.smart-tab]
enable = true

## Mappings
[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
W = ["move_next_sub_word_end"]
B = ["move_prev_sub_word_start"]

[keys.normal.space]
h = "@*%s<up><ret>"
b = ":sh git blame -L %{cursor_line},%{cursor_line} --no-color-by-age --color-lines %{buffer_name}"

[keys.normal.space.w]
d = ["vsplit"]

[keys.select.space]
h = "@*%s<up><ret>"

[keys.insert]
