[language-server.buf]
# cargo install buffer-language-server
command = "buffer-language-server"

[[language]]
name = "go"
auto-format = false
indent = { tab-width = 4, unit = "\t" }

[language-server.gopls.config]
# go install mvdan.cc/gofumpt@latest
"formatting.gofumpt" = false

[[language]]
name = "yaml"
auto-format = false
indent = { tab-width = 2, unit = " " }
formatter = { command = "yq" }

[[language]]
name = "json"
auto-format = false
indent = { tab-width = 2, unit = " " }
formatter = { command = "jq" }

[[language]]
name = "markdown"
auto-format = false
language-servers = [ "buf" ]

[[language]]
name = "git-commit"
auto-format = true
language-servers = [ "buf" ]

[[language]]
name = "rust"
auto-format = false
indent = { tab-width = 4, unit=" " }

[[language]]
# npm -i bash-language-server
name = "bash"
auto-format  = false
indent = { tab-width = 2, unit=" " }

