key_bindings:
  - { key: Paste,     action: Paste                                           }
  - { key: Copy,      action: Copy                                            }
  - { key: Equals,    mods: Command|Shift,      action: ResetFontSize         }
  - { key: Plus,      mods: Command,            action: IncreaseFontSize      }
  - { key: Minus,     mods: Command,            action: DecreaseFontSize      }
  - { key: V,         mods: Command,            action: Paste                 }
  - { key: C,         mods: Command,            action: Copy                  }
  - { key: N,         mods: Command,            action: CreateNewWindow       }
  - { key: G,         mods: Control,            chars: "\x66\x67\x0d"         }

