#!/bin/bash

## mise-cli
eval "$(mise activate ${SHELL##*/})"
export PATH="$HOME/.local/share/mise/shims:$PATH"
export MISE_GO_SET_GOROOT=true
export MISE_GO_SET_GOPATH=true

export PATH="/usr/local/bin:$PATH"

