#!/bin/zsh
# by randomowo

## nvm
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

## mysql@5.7
export PATH="$PATH:/opt/homebrew/opt/mysql@5.7/bin"

# homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# PATH
export PATH="/usr/local/sbin:$PATH"
export PATH="/opt/homebrew/opt/gnu-getopt/bin:$PATH"
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubun:$PATH"
export PATH="/opt/homebrew/bin:$PATH"

export PATH="/opt/homebrew/opt/openssl@3/bin:$PATH"
export PATH="/opt/homebrew/opt/python@3.11/bin:$PATH"
export PATH="/opt/homebrew/opt/e2fsprogs/sbin:$PATH"
