#!/bin/zsh
# by randomowo

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_COLLATE=C
export TERM="xterm-256color"

export EDITOR="nvim"

# mapping
export RCONFIGS="$HOME/.config"

# vim
export VIMDOTDIR="$RCONFIGS/vim"
export VIMINIT="source $VIMDOTDIR/.vimrc"

# sh
## all
HISTFILE='/tmp/.hist'
HISTSIZE=10000
SAVEHIST=0

## zsh
export ZDOTDIR="$RCONFIGS/zsh"

## nvm
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

## mysql@5.7
export PATH="$PATH:/opt/homebrew/opt/mysql@5.7/bin"

# homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# PATH
export PATH="/usr/local/sbin:$PATH"
export PATH="/opt/homebrew/opt/gnu-getopt/bin:$PATH"
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubun:$PATH"
export PATH="/opt/homebrew/bin:$PATH"

export PATH="/opt/homebrew/opt/openssl@3/bin:$PATH"
export PATH="/opt/homebrew/opt/python@3.10/bin:$PATH"
export PATH="/opt/homebrew/opt/e2fsprogs/sbin:$PATH"

[ -f ~/.azprofile ] && source ~/.azprofile
