#!/bin/sh
# _____ __    _____ _____ _____ _____ _____
# |  _  |  |  |     |  _  |   __|   __|   __|
# |     |  |__|-   -|     |__   |   __|__   |
# |__|__|_____|_____|__|__|_____|_____|_____|
#
# by randomowo

# check size
alias \
    dcap="df -h /" \
    sizeof="du -sh"

# counting folders and files
alias count="ls -a | wc -l"

# cd aliases
alias \
    ..='cd ..' \
    ...='cd ../..' \

# ls -> exa
alias \
    ls='exa' \
    l='exa -lahgF -a' \
    ll='exa -lhgF' \
    lst='exa --tree' \
    lt='exa -lahgF --tree' \

# git aliases
alias \
    git-adog="git log --all --decorate --oneline --graph" \
    git-undo="git revert  --soft HEAD~1" \
    gshf="git show --pretty='' --name-only" \
    gloglm="git log -1 --pretty=%B" \
    gtar="git diff --name-only -a | tar Tzcf - diff.tgz" \
    gcham="git commit --amend --author=\"$(git config user.name) <$(git config user.email)>\""

# python aliases
alias \
    cvenv='[ ! -d .venv ] && python -m venv .venv; . ./.venv/bin/activate' \
    dvenv='type deactivate >/dev/null && deactivate' \ rvenv='type deactivate >/dev/null && deactivate; rm -rf .venv' \
    pip='python -m pip' \
    upip='pip --disable-pip-version-check list --outdated --format=json | jq -r ".[].name" | xargs -I{} pip install --no-cache-dir -U "{}"' \
    pyprofile='python -m cProfile -o profile' \
    pytest='python -m pytest'

# programs
alias \
    x="lf" \
    vim='nvim' \
    e='vim' \


# network
alias \
    check-ciphers="nmap -sV --script ssl-enum-ciphers"

# docker
## containers
MYSQL='docker run --name mysql-for-tests --platform=linux/amd64 --rm -e MYSQL_ROOT_PASSWORD=password -p 3333:3306 -d'
POSTGRESQL='docker run --name postgres-for-tests --rm -e POSTGRES_PASSWORD=password -p 5439:5432 -d'
CLICKHOUSE='docker run --name clickhouse-for-tests --rm -p 9321:9000 -p 8321:8123 -d'

alias \
    dmysql=$MYSQL' mysql:5.7' \
    dvmysql=$MYSQL' -v mysql-test:/var/lib/mysql mysql:5.7' \
    dpostgres=$POSTGRESQL' postgres' \
    dvpostgres=$POSTGRESQL' -v postgres-test:/var/lib/postgresql postgres' \
    dclickhouse=$CLICKHOUSE' clickhouse/clickhouse-server:latest' \
    dvclickhouse=$CLICKHOUSE' -v clickhouse-test:/var/lib/clickhouse clickhouse/clickhouse-server:latest' \
    dubuntu='docker run --rm -it randomowo/ubuntu-vim bash' \
    cdubuntu='docker run --rm -it ubuntu bash'

## commands
alias \
    dpsi='docker ps --format="{{.Image}} -> {{.Names}}"'

# system specific aliases
[ -f $HOME/.caliasrc ] && source $HOME/.caliasrc
