#!/bin/sh
# _____ __    _____ _____ _____ _____ _____
# |  _  |  |  |     |  _  |   __|   __|   __|
# |     |  |__|-   -|     |__   |   __|__   |
# |__|__|_____|_____|__|__|_____|_____|_____|
#
# by randomowo

# check size
alias \
    dcap="df -h /" \
    sizeof="du -sh"

# counting folders and files
alias count="ls -a | wc -l"

# cd aliases
alias \
    ..='cd ..' \
    ...='cd ../..' \

# ls -> eza
alias \
    ls='eza' \
    l='eza -lahgF -a' \
    ll='eza -lhgF' \
    lst='eza --tree' \
    lt='eza -lahgF --tree' \

# python aliases
alias \
    cvenv='[ ! -d .venv ] && python -m venv .venv; . ./.venv/bin/activate' \
    dvenv='type deactivate >/dev/null && deactivate' \
    rvenv='type deactivate >/dev/null; deactivate; rm -rf .venv' \
    pip='python -m pip' \
    upip='pip --disable-pip-version-check list --outdated --format=json | jq -r ".[].name" | xargs -I{} pip install --no-cache-dir -U "{}"' \
    pyprofile='python -m cProfile -o profile' \
    pytest='python -m pytest'

function _yazi() {
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
    yazi "$@" --cwd-file="$tmp"
    if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
        builtin cd -- "$cwd"
    fi
    rm -f -- "$tmp"
}

# programs
alias \
    x="_yazi" \
    e="$EDITOR" \
    k="kubectl" \
    kx="kubectx"

# network
alias \
    check-ciphers="nmap -sV --script ssl-enum-ciphers"

# aliases
## git aliases
[ -f $HOME/.gitaliasrc ] && source $HOME/.gitaliasrc
## system specific aliases
[ -f $HOME/.caliasrc ] && source $HOME/.caliasrc
## other specific aliases (for only on machine aliases)
[ -f $HOME/.c2aliasrc ] && source $HOME/.c2aliasrc
