#!/bin/zsh

go install golang.org/x/tools/gopls@latest; \
go install github.com/go-delve/delve/cmd/dlv@latest; \
go install golang.org/x/tools/cmd/goimports@latest; \
go install mvdan.cc/gofumpt@latest \
go install mvdan.cc/sh/v3/cmd/shfmt@latest
