#!/bin/bash
~/.config/dunst/reload # dunst reload script
feh --bg-fill "$(cat ~/.cache/wal/wal)" # set up background image
~/.config/picom/launch.sh # picom reload script
killall -q dwmblocks; sleep 1; /usr/local/bin/dwmblocks #dwm status bar
