#!/bin/sh

# File preview handler for lf.

set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"
CACHE="${XDG_CACHE_HOME}:-$HOME/.cache"

# Note that the cache file name is a function of file information, meaning if
# an image appears in multiple places across the machine, it will not have to
# be regenerated once seen.

file="$1"

case "$(file --dereference --brief --mime-type -- "$file")" in
    text/troff) man ./ "$file" | col -b ;;
    text/* | */xml | application/json) bat --terminal-width "$(($4-2))" -f "$file" ;;
    audio/* | application/octet-stream) mediainfo "$file" || exit 1 ;;
    application/*zip) atool --list -- "$file" ;;
    *opendocument*) odt2txt "$file" ;;
    application/pgp-encrypted) gpg -d -- "$file" ;;
esac
exit 1

