#!/bin/sh
# _____ __    _____ _____ _____ _____ _____
# |  _  |  |  |     |  _  |   __|   __|   __|
# |     |  |__|-   -|     |__   |   __|__   |
# |__|__|_____|_____|__|__|_____|_____|_____|
#
# by randomowo

# programs
alias \
    ubrew="brew cleanup && brew upgrade && brew update && brew doctor" \
    ffmpeg="arch -arm64 ffmpeg" \
    yd="yt-dlp" \
    top="btm"

_uall() {
    cmds=( \
        "softwareupdate --all --install --force" \
        "ubrew" \
        "upip" \
        "mise upgrade" \
        "rustup upgrade" \
        "rustup update" \
    )

    for cmd in $cmds; do
        echo -e "\033[1;33mexecuting $cmd\033[0m"

        logcmd="$(echo "$cmd" | cut -d' ' -f1)"
        if eval "$cmd"; then
            echo -e "\033[0;32m$logcmd completed!\033[0m"
        else
            echo -e "\033[0;31m$logcmd failed!\033[0m"
        fi
    done
}

_hud() {
    enabled=$(launchctl getenv MTL_HUD_ENABLED)

    case "$1" in
        1|true)
            enabled=1
            ;;
        0|false)
            enabled=0
            ;;
        toggle)
            if [[ "$enabled" == "0" ]]; then
                enabled=1
            else
                enabled=0
            fi
            ;;
        *)
            echo -e "- \`1|true\` to enable\n- \`0|false\` to disable\n- \`toggle\` to toggle"
            return
            ;;
    esac

    launchctl setenv MTL_HUD_ENABLED "$enabled"
}

# shortcuts
alias \
    u="_uall" \
    hud="_hud"

