#!/bin/sh
# _____ __    _____ _____ _____ _____ _____
# |  _  |  |  |     |  _  |   __|   __|   __|
# |     |  |__|-   -|     |__   |   __|__   |
# |__|__|_____|_____|__|__|_____|_____|_____|
#
# by randomowo

# programs
alias \
    ubrew='brew cleanup && brew upgrade && brew update && brew doctor' \
    ffmpeg='arch -arm64 ffmpeg' \
    yd='yt-dlp' \
    prettier='prettier --config ~/.prettierrc.yaml'

# shotcuts
alias \
    u='softwareupdate --all --install --force; ubrew; echo -e "\033[0;32mbrew update complete!\033[0m" && upip; echo -e "\033[0;32mpip update complete!\033[0m" && npm update -g; echo -e "\033[0;32mnpm update complete!\033[0m"'

