#!/bin/sh
# _____ __    _____ _____ _____ _____ _____
# |  _  |  |  |     |  _  |   __|   __|   __|
# |     |  |__|-   -|     |__   |   __|__   |
# |__|__|_____|_____|__|__|_____|_____|_____|
#
# by randomowo

# programs
alias \
    ubrew="brew upgrade && brew update && brew doctor && brew cleanup" \
    ffmpeg="arch -arm64 ffmpeg" \
    yd="yt-dlp" \
    top="btm"

_ucargobins() {
    cargo install $(cargo install --list | egrep '^[a-z0-9_-]+ v[0-9.]+:$' | cut -f1 -d' ')
}

_uall() {
    cmds=( \
        "softwareupdate --all --install --force" \
        "ubrew" \
        "upip" \
        "mise upgrade" \
        "rustup update" \
        "_ucargobins"
    )

    for cmd in $cmds; do
        echo -e "\033[1;33mexecuting $cmd\033[0m"

        logcmd="$(echo "$cmd" | cut -d' ' -f1)"
        if eval "$cmd"; then
            echo -e "\033[0;32m$logcmd completed!\033[0m"
        else
            echo -e "\033[0;31m$logcmd failed!\033[0m"
        fi
    done
}

_hud() {
    enabled=$(launchctl getenv MTL_HUD_ENABLED)

    case "$1" in
        1|true)
            enabled=1
            ;;
        0|false)
            enabled=0
            ;;
        toggle)
            if [[ "$enabled" == "0" ]]; then
                enabled=1
            else
                enabled=0
            fi
            ;;
        *)
            echo -e "- \`1|true\` to enable\n- \`0|false\` to disable\n- \`toggle\` to toggle"
            return
            ;;
    esac

    launchctl setenv MTL_HUD_ENABLED "$enabled"
}

_ugomod() {
    if [ ! -f './go.mod' ]; then
        echo "missing go.mod in CWD"
        exit 1
    fi

    for dep in $(cat go.mod | grep -E '^ ' | sed -e 's/\/\/\ indirect//g' | cut -d ' ' -f1 | xargs); do
        go get -u "$dep";
    done
}

_cd() {
    if command -v zoxide &>/dev/null; then
        type z >/dev/null || eval "$(zoxide init zsh)"

        z "$@"
    else
        \cd "$@"
    fi
}

# shortcuts
alias \
    u="_uall" \
    hud="_hud" \
    ugomod="_ugomod" \
    ucargobins="_ucargobins" \
    cd="_cd"
