[aliases]
d = ["diff"]
rm = ["abandon"]
t = ["tag"]
sh = ["show"]
st = ["status"]
l = ["log"]
c = ["commit"]
s = ["squash"]
n = ["new"]
co = ["edit"]
e = ["edit"]
ds = ["describe"]
rb = ["rebase"]
b = ["bookmark"]
rv = ["backout"]
rs = ["restore"]
sp = ["split"]
w = ["workspace"]

