[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"
title = "(ﾉ･д･)ﾉ"
option_as_alt = "Both"

[window.dimensions]
columns = 150
lines = 45

[window.padding]
x = 5
y = 5

