#!/bin/zsh
# by randomowo

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_COLLATE=C
export TERM="xterm-256color"

#export EDITOR="nvim -i NONE"
export EDITOR="hx"

# mapping
export RCONFIGS="$HOME/.config"

export GPG_TTY=$(tty)

# sh
## all
HISTFILE='/tmp/.hist'
HISTSIZE=10000
SAVEHIST=10000

## zsh
export ZDOTDIR="$RCONFIGS/zsh"

# system specific zprofile
[ -f $HOME/.czprofile ] && source $HOME/.czprofile

# machine specific zprofile
[ -f $HOME/.c2zprofile ] && source $HOME/.c2zprofile
