#!/bin/sh
# _____ __    _____ _____ _____ _____ _____ 
# |  _  |  |  |     |  _  |   __|   __|   __|
# |     |  |__|-   -|     |__   |   __|__   |
# |__|__|_____|_____|__|__|_____|_____|_____|
#                                            
# by randomowo

# connect by ssh to my server
alias sshm="ssh makromant@makromant.myjino.ru"

# check size
alias \
	dcap="df -h /" \
	sizeof="du -sh"

# counting folders and files
alias count="ls -a | wc -l"

# git aliases
alias \
	git-adog="git log --all --decorate --oneline --graph" \
	git-undo="git revert  --soft HEAD~1"

# remove unused packages
alias cleanup='yay -Rns $(yay -Qtdq) && yay -Yc'

# update python packages
alias upip='pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 sudo -H pip install --ignore-installed -U'

# ls -> exa
alias \
	ls='exa' \
	l='exa -lahgF -a' \
	ll='exa -lhgF' \
	lst='exa --tree' \
	lt='exa -lahgF --tree' \

# programs
alias \
	x='ranger' \
    tmux='tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf "$@"' \
	calcurse='calcurse -D $PROGPATH/calcurse' \
	vim='nvim' \
	cleaner='bleachbit' \
	hex='hexcurse' \
	mocp='mocp -M "$XDG_CONFIG_HOME/moc"' \
	asciimpv='CACA_DRIVER=ncurses mpv --quiet -vo=caca "$@"' \
	mix='pulsemixer'

# cd aliases
alias \
	..='cd ..' \
	...='cd ../..' \
	cu='cd $UNI/' \
	enru='transs -er "$@"' \
	ruen='transs -re "$@"'

# games
alias \
	go='gnugo' \
	1go='gnugo --boardsize 9 --level 1'

# devour applications
alias \
    mpv='devour mpv' \
    sxiv='devour sxiv' \
    zathura='devour zathura'
