[colors.bright]
black = "0x928273"
blue = "0x83a497"
cyan = "0x8ebf7b"
green = "0xb8ba26"
#magneta = "0xd2859a"
red = "0xfa4834"
white = "0xebdab1"
yellow = "0xf9bc2f"

[colors.cursor]
cursor = "0xebdab1"
text = "0x282727"

[colors.normal]
black = "0x282727"
blue = "0x458487"
cyan = "0x689c69"
green = "0x98961a"
#magneta = "0xb06185"
red = "0xcb231d"
white = "0xa89883"
yellow = "0xd69821"

[colors.primary]
background = "0x282727"
foreground = "0xebdab1"

