# Font configuration
font:

  normal:
    family: mononoki Nerd Font
    style: Regular

  size: 12.0

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

#  use_thin_strokes: true

draw_bold_text_with_bright_colors: true

