#!/bin/bash
# by randomowo

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_COLLATE=C

export EDITOR="nvim"

# mapping
export RCONFIGS="$HOME/.config"

# vim
export VIMDOTDIR="$RCONFIGS/vim"
export VIMINIT="source $VIMDOTDIR/.vimrc"
export NVIM_LOG_FILE="/dev/null"

# sh
## all
HISTFILE='/tmp/.hist'
HISTSIZE=10000
SAVEHIST=0

## zsh
export ZDOTDIR="$RCONFIGS/zsh"

