config-version = 2

after-startup-command = []

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

persistent-workspaces = ["1", "2", "3", "4", "5", "Q", "W", "E"]

on-mode-changed = []

key-mapping.preset = 'qwerty'

[gaps]
    inner.horizontal = 5
    inner.vertical =   5
    outer.left =       5
    outer.bottom =     5
    outer.top =        5
    outer.right =      5

[workspace-to-monitor-force-assignment]
    1 = 'main'
    2 = 'main'
    3 = 'main'
    4 = 'main'
    5 = 'main'
    Q = 'secondary'
    W = 'secondary'
    E = 'secondary'

[mode.main.binding]
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-e = 'workspace E'
    alt-q = 'workspace Q'
    alt-w = 'workspace W'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-e = 'move-node-to-workspace E'
    alt-shift-q = 'move-node-to-workspace Q'
    alt-shift-w = 'move-node-to-workspace W'

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    alt-shift-semicolon = 'mode service'

    alt-f = 'layout floating tiling'
    alt-m = 'mode monitor'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']

[mode.monitor.binding]
    esc = 'mode main'

    alt-shift-h = ['move-node-to-monitor --focus-follows-window left']
    alt-shift-j = ['move-node-to-monitor --focus-follows-window down']
    alt-shift-k = ['move-node-to-monitor --focus-follows-window up']
    alt-shift-l = ['move-node-to-monitor --focus-follows-window right']
