[settings]
go_default_packages_file = "$HOME/.config/mise/default-go-packages"
python_default_packages_file = "$HOME/.config/mise/default-pips"
experimental = true
python_compile = true

[tools]
python = "latest"
go = "latest"
bun = "latest"

