[settings]
python_default_packages_file = "$HOME/.config/mise/default-pips"
experimental = true
python_compile = false
go_set_gobin = false

[tools]
python = "latest"
go = "latest"
bun = "latest"
node = "latest"

