[settings]
go_default_packages_file = "$HOME/.config/mise/default-go-packages"
python_default_packages_file = "$HOME/.config/mise/default-pips"

[tools]
python = "latest"
go = "latest"
node = "latest"
bun = "latest"
rust = "latest"

