[settings]
python.default_packages_file = "$HOME/.config/mise/default-pips"
python.compile = false

go.set_gobin = false
go.set_goroot = true
go.default_packages_file = "$HOME/.config/mise/default-go"

[tools]
python = "latest"
go = "latest"
bun = "latest"
fzf = "latest"
